import {
    GuitarSrc,
    GuitarTitle,
    GuitarPrice,
    GuitarsId,
    ViolinId,
    ViolinSrc,
    ViolinTitle,
    ViolinPrice,
    UkuleleId,
    UkuleleSrc,
    UkuleleTitle,
    UkulelePrice,
} from "core/enums/instruments-data";

export const guitarData = [
    {
        id: GuitarsId.MarcusMiller,
        image: GuitarSrc.MarcusMiller,
        title: GuitarTitle.MarcusMiller,
        price: GuitarPrice.MarcusMiller,
        isHasColor: false,
        colors: [],
    },
    {
        id: GuitarsId.Fender,
        image: GuitarSrc.Fender,
        title: GuitarTitle.Fender,
        price: GuitarPrice.Fender,
        isHasColor: false,
        colors: [],
    },
    {
        id: GuitarsId.SireMarcusMiller,
        image: GuitarSrc.SireMarcusMiller,
        title: GuitarTitle.SireMarcusMiller,
        price: GuitarPrice.SireMarcusMiller,
        isHasColor: false,
        colors: [],
    },
    {
        id: GuitarsId.Yamaha,
        image: GuitarSrc.Yamaha,
        title: GuitarTitle.Yamaha,
        price: GuitarPrice.Yamaha,
        isHasColor: false,
        colors: [],
    },
    {
        id: GuitarsId.FenderS,
        image: GuitarSrc.FenderS,
        title: GuitarTitle.FenderS,
        price: GuitarPrice.FenderS,
        isHasColor: false,
        colors: [],
    },
    {
        id: GuitarsId.YamahaQ,
        image: GuitarSrc.YamahaQ,
        title: GuitarTitle.YamahaQ,
        price: GuitarPrice.YamahaQ,
        isHasColor: false,
        colors: [],
    },
];

export const violinsData = [
    {
        id: ViolinId.GligaGems,
        image: ViolinSrc.GligaGems,
        title: ViolinTitle.GligaGems,
        price: ViolinPrice.GligaGems,
        isHasColor: false,
        colors: [],
    },
    {
        id: ViolinId.AntonioWang,
        image: ViolinSrc.AntonioWang,
        title: ViolinTitle.AntonioWang,
        price: ViolinPrice.AntonioWang,
        isHasColor: false,
        colors: [],
    },
    {
        id: ViolinId.CorinaOrquestra,
        image: ViolinSrc.CorinaOrquestra,
        title: ViolinTitle.CorinaOrquestra,
        price: ViolinPrice.CorinaOrquestra,
        isHasColor: false,
        colors: [],
    },
    {
        id: ViolinId.GligaExtra,
        image: ViolinSrc.GligaExtra,
        title: ViolinTitle.GligaExtra,
        price: ViolinPrice.GligaExtra,
        isHasColor: false,
        colors: [],
    },
    {
        id: ViolinId.AntonioWangFeritage,
        image: ViolinSrc.AntonioWangFeritage,
        title: ViolinTitle.AntonioWang,
        price: ViolinPrice.AntonioWang,
        isHasColor: false,
        colors: [],
    },
    {
        id: ViolinId.Stentor,
        image: ViolinSrc.Stentor,
        title: ViolinTitle.Stentor,
        price: ViolinPrice.Stentor,
        isHasColor: false,
        colors: [],
    },
];

export const ukuleleData = [
    {
        id: UkuleleId.KalaK,
        image: UkuleleSrc.KalaK,
        title: UkuleleTitle.KalaK,
        price: UkulelePrice.KalaK,
        isHasColor: false,
        colors: [],
    },
    {
        id: UkuleleId.Figure,
        image: UkuleleSrc.Figure,
        title: UkuleleTitle.Figure,
        price: UkulelePrice.Figure,
        isHasColor: true,
        colors: [{ color: "#1396B1" }, { color: "#DD9738" }],
    },
    {
        id: UkuleleId.KalaB,
        image: UkuleleSrc.KalaB,
        title: UkuleleTitle.KalaB,
        price: UkulelePrice.KalaB,
        isHasColor: false,
        colors: [],
    },
];
